package com.ssm_top1.pojo;

public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.gradeID
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    private Integer gradeid;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.gradeName
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    private String gradename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.gradeID
     *
     * @return the value of grade.gradeID
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public Integer getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.gradeID
     *
     * @param gradeid the value for grade.gradeID
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public void setGradeid(Integer gradeid) {
        this.gradeid = gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.gradeName
     *
     * @return the value of grade.gradeName
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public String getGradename() {
        return gradename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.gradeName
     *
     * @param gradename the value for grade.gradeName
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public void setGradename(String gradename) {
        this.gradename = gradename == null ? null : gradename.trim();
    }
}