package com.ssm_top1.pojo;

public class Subjects {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjects.subjectNo
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    private Integer subjectno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjects.subjectName
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    private String subjectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjects.classHour
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    private Integer classhour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjects.gradeID
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    private Integer gradeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subjects.subjectNo
     *
     * @return the value of subjects.subjectNo
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public Integer getSubjectno() {
        return subjectno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subjects.subjectNo
     *
     * @param subjectno the value for subjects.subjectNo
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public void setSubjectno(Integer subjectno) {
        this.subjectno = subjectno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subjects.subjectName
     *
     * @return the value of subjects.subjectName
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public String getSubjectname() {
        return subjectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subjects.subjectName
     *
     * @param subjectname the value for subjects.subjectName
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public void setSubjectname(String subjectname) {
        this.subjectname = subjectname == null ? null : subjectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subjects.classHour
     *
     * @return the value of subjects.classHour
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public Integer getClasshour() {
        return classhour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subjects.classHour
     *
     * @param classhour the value for subjects.classHour
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public void setClasshour(Integer classhour) {
        this.classhour = classhour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subjects.gradeID
     *
     * @return the value of subjects.gradeID
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public Integer getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subjects.gradeID
     *
     * @param gradeid the value for subjects.gradeID
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    public void setGradeid(Integer gradeid) {
        this.gradeid = gradeid;
    }
	@Override
	public String toString() {
		return "Subjects [subjectno=" + subjectno + ", subjectname=" + subjectname + ", classhour=" + classhour
				+ ", gradeid=" + gradeid + "]";
	}

	public Subjects(Integer subjectno, String subjectname, Integer classhour, Integer gradeid) {
		super();
		this.subjectno = subjectno;
		this.subjectname = subjectname;
		this.classhour = classhour;
		this.gradeid = gradeid;
	}
	public Subjects() {
		super();
	}
	
}