package com.ssm_top1.mapper;

import com.ssm_top1.pojo.Subjects;
import com.ssm_top1.pojo.SubjectsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubjectsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    long countByExample(SubjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    int deleteByExample(SubjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    int deleteByPrimaryKey(Integer subjectno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    int insert(Subjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    int insertSelective(Subjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    List<Subjects> selectByExample(SubjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    Subjects selectByPrimaryKey(Integer subjectno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") Subjects record, @Param("example") SubjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    int updateByExample(@Param("record") Subjects record, @Param("example") SubjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    int updateByPrimaryKeySelective(Subjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Mon Jul 01 22:14:23 CST 2019
     */
    int updateByPrimaryKey(Subjects record);
}